#!/usr/bin/env bash
# This script lists the content of the current directory, displaying only the part after the first dash
for file in *
do
    if [[ "$file" == *-* ]]
        then
                echo "${file#*-}"
                    fi
                    done
